# fly.toml app configuration file generated for tamagawa-golf on 2023-11-13T00:20:52+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tamagawa-golf"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
